fruits = ["apple", "banana", "orange"]
print(fruits)
fruits.append("grape")
print(fruits)
fruits.insert(1, "peach")
print(fruits)
fruits.remove("banana")
print(fruits)
fruits.pop(1)
print(fruits)
fruits.reverse()
print(fruits)
fruits.sort()
print(fruits)